version: "3.3"

services:
  mysqldb:
    image: mysql:5.7.19
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ALLOW_EMPTY_PASSWORD=YES
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ~/docker-volumes/mysql_5_7_19-data:/var/lib/mysql
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    networks:
      - backend
  web-app:
    build: .
    image: clebersonp/spring-boot-docker
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306     
    depends_on:
      - mysqldb
    networks:
      - backend

networks:
  backend:
    driver: "bridge"